### ISSUE TITLE
Biopython complains about PomBase chromosome contig

### ISSUE THREAD

**Issue by manulera** [pombase/allele_qc#1]
Extra space in the first row before `20128BP`.

**Comment by ValWood** [comment]
removed.

**Comment by ValWood** [comment]
OK, fixed correctly.

If the update runs it should be  updated on the FTP site overnight.
The update frequency might be a little less while @kimrutherford  is away

**Comment by manulera** [comment]
Hi @ValWood I am checking other things, and noticed that certain genome coordinates do not match in the pombe-embl files and the FTP server. Example:

```
FTP > chromosome1

FT   CDS             5064305..5066231
FT                   /colour=13
FT                   /controlled_curation="term=wtf element;
FT                   db_xref=PMID:12952871; date=20070223"

pombe-embl > chromosome1

FT   CDS             join(5064781..5064919,5065087..5065332,5065380..5065610,5065652..5065705,5065760..5065836)
FT                   /colour=13
FT                   /controlled_curation="term=wtf element;
FT                   db_xref=PMID:12952871; date=20070223"
```

**Comment by ValWood** [comment]
@kimrutherford 
maybe the ftp site is not updating:

/systematic_id="SPAC2E12.05"
/controlled_curation="term=warning, gene structure updated; db_xref=PMID:28631610; date=20200501"

**Comment by kimrutherford** [comment]
It looks OK to me: https://www.pombase.org/nightly_update/pombe-embl/

**Comment by manulera** [comment]
Hi Val,

> [Chromosome contigs] in enriched EMBL-based format for loading into Artemis
https://www.pombase.org/data/genome_sequence_and_features/artemis_files/

These are the ones I downloaded, and they are different in the FTP server compared to svn as in the comment above. You can double-check on your side for chromosome1 wtf element.

**Comment by kimrutherford** [comment]
> I think the header might cause problems for Artemis

Artemis should ignore any header lines.  It can read standard EMBL/Genbank entries, including the header.

**Comment by kimrutherford** [comment]
> OK, got it, it says on the downloads page
> https://www.pombase.org/downloads/genome-datasets

It's here if you'd like to edit it:
https://github.com/pombase/website/blob/master/src/docs/downloads/genome-datasets.md

I suggest we link to the files in the release directory: https://www.pombase.org/releases/latest/pombe-embl/

**Comment by ValWood** [comment]
I'm. a bit confused. @manu which files are you using on the FTP directory?

**Comment by manulera** [comment]
I was using these:

https://www.pombase.org/data/genome_sequence_and_features/artemis_files/

From what Kim is saying I gather that the latest version is always:

https://www.pombase.org/releases/latest/pombe-embl/

I think we should remove the other contig files or put them somewhere where it is clear that they are previous versions.

**Comment by ValWood** [comment]
https://www.pombase.org/data/genome_sequence_and_features/artemis_files/
should also be the current versions shouldn't they @kimrutherford 
(we can sort this when you get back)

**Comment by ValWood** [comment]
I will add this to the agenda for Monday

**Comment by kimrutherford** [comment]
> I think we should remove the other contig files or put them somewhere where it is clear that they are previous versions.

I agree.

> should also be the current versions shouldn't they

I think it was copied over from the Ensembl version of PomBase.
It's just a copy of this SVN directory: `pombe-embl/ftp_site/pombe/genome_sequence_and_features/artemis_files/`

**Comment by manulera** [comment]
> Extra space in the first row before `20128BP`.

@kimrutherford this change is in the last svn revision but not in https://www.pombase.org/releases/latest/ this is done monthly, I guess?

**Comment by kimrutherford** [comment]
> this is done monthly, I guess?

Yep, it's monthly.  Usually the release is done on the 1st day of the month, unless there's a problem with that night's load.

https://github.com/pombase/pombase-chado/wiki/Monthly-releases
