### ISSUE TITLE
Internal Server Error for /check_modification

### ISSUE THREAD

**Issue by kimrutherford** [pombase/allele_qc#104]
Hi @manulera

Sorry for the last minute call for help.

The /check_modification API is working well but I notice a case that causes an error:

```
systematic_id: SPBC18H10.20c
sequence_position: K4
mod_code: MOD:01221
```

I think the `MOD:01221` might be the problem because other ID work OK.

**Comment by manulera** [comment]
The problem is here: https://github.com/pombase/allele_qc/blob/master/make_mod_dict.py#L29-L30

It was only storing in the dictionary the mods that exist in PomBase already. I can fix that and a better message when an unknown mod is passed

**Comment by manulera** [comment]
Hi @kimrutherford, now that request should work. I have made it so that make_mod_dict.py includes all mod codes in the ontology, not only those that were used in PomBase.
