### ISSUE TITLE
Different sequence of tsn1 in a 2010 paper

### ISSUE THREAD

**Issue by manulera** [pombase/allele_qc#11]
cc @ValWood

From https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2875027/

They have a different protein sequence for tsn1, but tsn1 gene features did not change in our svn repository.

```
# Their sequence
MNKSIFIQLQDQIDKEHSIREKLTAEVDLLDEKLRVLQLLLANCEQSRNENLQEKEHGLTLEDLENQEEILEALEIIKSKTRGLAELASNFPYYKYNGVWDRSIQKVVYLYLLASWTGRLDKSLRPTYSLLSLSEVGQILQVPVFPEESTFHLSIEQYLHAVLSLCSELARQSVNSVISGNYHIPFEALNTIQKVHSSFQVLSLKNDSLRRHFDGLKYDLKRSEDVVYDLRIHKLV*
                                                              *
MNKSIFIQLQDQIDKEHSIREKLTAEVDLLDEKLRVLQLLLANCEQ----------------NLENQEEILEALEIIKSKTRGLAELASNFPYYKYNGVWDRSIQKVVYLYLLASWTGRLDKSLRPTYSLLSLSEVGQILQVPVFPEESTFHLSIEQYLHAVLSLCSELARQSVNSVISGNYHIPFEALNTIQKVHSSFQVLSLKNDSLRRHFDGLKYDLKRSEDVVYDLRIHKLV*
# Pombase sequence

```

**Comment by ValWood** [comment]
Right our sequence predates 2010, maybe I got the splicing incorrect (I will check). Usually we pick these up at annotation time, but I can't see that they reported a different sequence from PomBase...

**Comment by ValWood** [comment]
The region is not super conserved but I think the splice is correct:

<img width="692" alt="Screenshot 2022-11-02 at 13 10 45" src="https://user-images.githubusercontent.com/7359272/199498345-5944a1ab-c382-4522-95c7-71305629d71d.png">
<img width="660" alt="Screenshot 2022-11-02 at 13 10 51" src="https://user-images.githubusercontent.com/7359272/199498359-9eb6f605-dc64-464d-a363-8f379f40b344.png">
<img width="654" alt="Screenshot 2022-11-02 at 13 11 20" src="https://user-images.githubusercontent.com/7359272/199498376-7a69e257-58c5-4b4a-9d1f-060a58298212.png">


there is a single residue indel as opposed to a large segment of additional amino acids that are not conserved in any related species. This coupled with the perfect splice acceptor/branch/donor makes me believe it is real. I think the authors probably did  a prediction on the genomic sequence, which would likely miss an in-frame intron.

**Comment by ValWood** [comment]
Im going to reannotate to 
RNAse complex
RNA processing
by ISO to PMID: 36098897

**Comment by manulera** [comment]
This is now picked up by the pipeline.
