### ISSUE TITLE
Failed job

### ISSUE THREAD

**Issue by manulera** [pombase/allele_qc#110]
Hi @kimrutherford

This job failed:

https://github.com/pombase/allele_qc/actions/runs/6445032677/job/17520758110

I don't immediately see why. If you can quickly identify why let me know, otherwise I will dig into it.

**Comment by kimrutherford** [comment]
Hi Manu.  It looks like a temporary GitHub or Ubuntu problem:

```
Err:28 mirror+file:/etc/apt/apt-mirrors.txt focal-updates/universe amd64 libnode64 amd64 10.19.0~dfsg-3ubuntu1.1
  404  Not Found [IP: 52.154.174.208 80]
Ign:38 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 nodejs amd64 10.19.0~dfsg-3ubuntu1.1
```

So I suggest trying again in a few hours.

**Comment by manulera** [comment]
Alrightt thanks! I thought maybe it had to do with apt-get.

**Comment by manulera** [comment]
Hi @kimrutherford, the script failed again. It says to include `apt-get update`, would that make a difference you think? Not familiar with linux dep managers.

**Comment by kimrutherford** [comment]
Hi Manu.

> It says to include apt-get update, would that make a difference you think?

I think it would help.  I suggest adding this on the line before `sudo apt-get install subversion -y`:

```
sudo apt-get update
```

**Comment by manulera** [comment]
It works now. Thanks!
