### ISSUE TITLE
Special warning for histones

### ISSUE THREAD

**Issue by manulera** [pombase/allele_qc#15]
If they have been fixed and they have the description in the name

**Comment by ValWood** [comment]
did I mention that histones are a special case, and that people number them after the initiator met is removed?
So Histone H-3 K14 is actually at position 15 (actually, this applies when people discuss modifications, I presume it applies to describing mutants too?)

**Comment by ValWood** [comment]
Yes it does, so 
[hht1Δ hht2-S86A, S87A (

is actually S87 and S88 in the sequence.
This convention holds for all species.

**Comment by manulera** [comment]
We discussed this in https://github.com/pombase/curation/issues/3453
