### ISSUE TITLE
Github action / commit data / copy to container

### ISSUE THREAD

**Issue by manulera** [pombase/allele_qc#42]
Hi @kimrutherford. I have done what we discussed yesterday:

* The `data` directory is committed to the repo.
* There is a [github action](https://github.com/pombase/allele_qc/blob/master/.github/workflows/run_pipeline.yml) that runs the pipeline
    * Downloads necessary files + runs the python scripts + commits if any tsv file has changed
    * Can be triggered from the command line, see [trigger_action.sh](https://github.com/pombase/allele_qc/blob/master/trigger_action.sh)
    * I think this could be triggered at the start of the overnight run, to make sure it will have finished by the time the docker container is built (there is some delay).
* Now the docker file copies the files from the `data` directory instead of downloading + generating them in the container, so in the overnight run you could:
    * Pull latest changes
    * Build container

**Comment by kimrutherford** [comment]
That's great.  Thanks!

**Comment by kimrutherford** [comment]
> I think this could be triggered at the start of the overnight run,

Should we run this in an Action with a GitHub schedule/cron?
