### ISSUE TITLE
"Systematic id does not exist" for SPNCRNA.1715

### ISSUE THREAD

**Issue by kimrutherford** [pombase/allele_qc#45]
Hi @manulera 

I tried a few different genes to test the download buttons and found that "SPNCRNA.1715" returns:
```json
{"detail":"Systematic id does not exist"} 
```

Do you have any idea why that ID isn't found?

https://curation.pombase.org/allele_qc/genome_region?systematic_id=SPNCRNA.1715&format=genbank&upstream=0&downstream=0

**Comment by manulera** [comment]
Hi @kimrutherford. The systematic_id is new, it did not exist in the revision that was being used. It actually comes from a publication I curated recently. I am updating now and will double-check that it works. If it does I will close

**Comment by manulera** [comment]
Ok, fixed with https://github.com/pombase/allele_qc/commit/847869daea608f1c10077b220bbb5dff2a97fce2

**Comment by kimrutherford** [comment]
> It actually comes from a publication I curated recently.

That explains it!  Sounds like I was a bit unlucky to be testing with that ID.  :-)

Thanks for the fix.
