### ISSUE TITLE
General improvements

### ISSUE THREAD

**Issue by manulera** [pombase/allele_qc#47]
Hi @kimrutherford

I have made some general improvements to the repo in this PR: https://github.com/pombase/allele_qc/pull/46

* I have changed from POST to GET request on all the important endpoints.
* I added tests to the api endpoints (and fixed a bunch of fixes on the way), that are ran on push / PR.
* I have added support for genes that have multiple transcripts:
    * For check_allele or fixes endpoints, the main `.1` transcript is used
    * For the genome_region endpoint the longest transcript is used. This is not the optimal solution (the short one may not fully overlap with the long one), but users can simply choose a longer upstream / downstream value
    * This is documented in the API docs
        <details>
        <summary>Click me</summary>

        ![Screenshot 2023-04-19 at 18 06 57](https://user-images.githubusercontent.com/22526102/233148988-8335fc27-cd91-4ed7-994e-2171a4087e5e.png)

        ![Screenshot 2023-04-19 at 18 07 08](https://user-images.githubusercontent.com/22526102/233149048-32616fa4-a325-4dcc-85c1-8637a719ec4d.png)

        </details>
* Refactored it overall so that there is less code repetition, hopefully it will be easier to maintain (I can take care of it even after PomBase).

**Comment by kimrutherford** [comment]
Thanks!

> Refactored it overall so that there is less code repetition, hopefully it will be easier to maintain (I can take care of it even after PomBase).

We promise not to bother you too much once you've left PomBase.  :-)
