### ISSUE TITLE
tor2-13

### ISSUE THREAD

**Issue by ValWood** [pombase/allele_qc#54]
In https://github.com/pombase/allele_qc/blob/master/change_log/allele_manual_changes_formatted_19042023.tsv

SPBC216.07c | tor2-13 | C2163R,I2280V,G2205L

but currently
https://www.pombase.org/genotype/tor2-13-Q2305L-amino_acid_mutation-expression-not_assayed_or_wild_type

seems odd?

**Comment by manulera** [comment]
Yes, my mistake. This is from the manual fixes. The right description is:

C2163R,I2280V,Q2305L

I will fix in canto now. Good catch. How did you come across?

**Comment by ValWood** [comment]
I can't remember! Worryingly I can't remember **ever** looking at this file:
https://github.com/pombase/allele_qc/blob/master/change_log/allele_manual_changes_formatted_19042023.tsv

**Comment by manulera** [comment]
You must have downloaded it for the numbers you gave in the Pombe meeting presentation

**Comment by ValWood** [comment]
I notice in this file some of the description include additional text to what we would normally include in the description, which we usually constrain on the information described in the prompt.

For example


SPAC23C4.05c | les1(1-291) | C-terminal truncation 292-431
We wouldn't usually provide "C-terminal truncation" in the formal description, only the deleted residues

SPAC7D4.04 | atg11(522-552)-LZ | 522-552-LZ motif
We would not usually include -LZ motif

SPCC736.15 | pil1N | pil1(1-266)
We don't usually put gene names in descriptions (except for chimeras)

SPAC14C4.01c | atg43-deltaC60-GFP | 1-184delta,Mt tethered
This one, the normal localization of atg43 is mitochondrion?

I guess it isn't a problem to have additional text in the description, it's just that we never did it so far (at least intentionally), if the description did not fit the formal one, we described as "other".
I guess my main worry is how we convey to the users what is allowed in the description.

Maybe we should only allow  information that is not possible to extract from the "formal" description.
Or perhaps it doesn't matter as long as the "formal" part is present in the string?

**Comment by ValWood** [comment]
>You must have downloaded it for the numbers you gave in the Pombe meeting presentation

Yes, I did. I have no idea how I spotted that particular one though!

**Comment by manulera** [comment]
> I notice in this file some...

Those are the old descriptions. The corrected value is in the column `change_description_to`
