### ISSUE TITLE
Retroactively fix manual changes without change_name_to

### ISSUE THREAD

**Issue by manulera** [pombase/allele_qc#56]
For alleles that contained the description and were changed manually, but I forgot to use change_name_to, retroactively fix names using the change-Log 

## After

- Create Issue to flag changes of names that included the description -> in red or add warning or something.
	- Make the list in the repo
	- Announce to people (soon you can find them)

**Comment by manulera** [comment]
Hi @kimrutherford. We discussed this before Japan, I think.

Basically I did a bunch of manual fixes in the past. In some of them, I changed the description of the allele, but I should have changed the name as well,as the description was contained in the name. For example in `isu1-D37A` I fixed the description from `D37A` to `D90A`, but forgot to change the name to `isu1-D90A`. The file below in the usual format can be used to fix 56 of these cases:

Some errors might remain after these fixes, because of the fringe case explained here: https://github.com/pombase/pombase-chado/issues/1095

To make sure we fix those as well, let me know when this fixes are incorporated and I will manually check the logs that report the allele names not starting with the gene name. Then all should be fixed, I think.

**Comment by manulera** [comment]
@kimrutherford this is the file:

https://github.com/pombase/allele_qc/blob/master/change_log/allele_manual_changes_formatted_where_description_was_in_name_29062023.tsv

**Comment by kimrutherford** [comment]
Hi @manulera

I've applied those changes.  There was one error:
```
ignoring duplicate allele_name: prp10-E622D
```
from this line:
```
SPAC27F1.09c prp10-E622D     E622D   prp10-E622D
```

**Comment by manulera** [comment]
Thanks @kimrutherdord. I don't know where that line came from, but I see in the website that all is fine. Thanks!
