### ISSUE TITLE
Old modified residue no longer in gene structure

### ISSUE THREAD

**Issue by manulera** [pombase/allele_qc#62]
Hello @ValWood @KimRutherford

I was having a look at the protein modifications with sequence errors, and I realised there is a scenario I was not contemplating. For example, data from `PMID:29996109` and `PMID:33823663` (high-throughput phosporylation sites) says that position S4 is phosphorylated in mmb1. There is an old sequence of mmb1 that had S4, but now that Serine maps to nothing, because we moved the starting ATG forward:

```
> current sequence
----------------MLQRLEQL
> old sequence
MPGSPSQEPLAEAESNMLQRLEQL
```

Below are all modifications affected by this. If we drop annotations to these residues (I can do this manually), we can then import fixes for ~60 modifications that rely on old sequences (they were held back because of this "missing" residues).

| SPAC3H1.05   | ste24  | MOD:00046 | tryptic phosphopeptide mapping assay evidence used in automatic assertion | S12 |                            | PMID:30726745 | 4896 | 2019-02-05 | S12 | ? | old_coords_fix, revision 8148: join(1938900..1939004,1939075..1940394)             |
| ------------ | ------ | --------- | ------------------------------------------------------------------------- | --- | -------------------------- | ------------- | ---- | ---------- | --- | - | ---------------------------------------------------------------------------------- |
| SPAC57A7.12  | ssz1   | MOD:00046 | experimental evidence                                                     | S12 | present_during(GO:0000087) | PMID:21712547 | 4896 | 2011-06-28 | S12 | ? | old_coords_fix, revision 8148: complement(join(1515089..1516663,1516789..1516914)) |
| SPBC25B2.07c | mmb1   | MOD:00046 | tryptic phosphopeptide mapping assay evidence used in automatic assertion | S4  |                            | PMID:29996109 | 4896 | 2018-07-10 | S4  | ? | old_coords_fix, revision 1381: complement(2609038..2610591)                        |
| SPBC25B2.07c | mmb1   | MOD:00046 | tryptic phosphopeptide mapping assay evidence used in automatic assertion | S4  |                            | PMID:33823663 | 4896 | 2022-03-08 | S4  | ? | old_coords_fix, revision 1381: complement(2609038..2610591)                        |
| SPBC25B2.07c | mmb1   | MOD:00046 | tryptic phosphopeptide mapping assay evidence used in automatic assertion | S6  |                            | PMID:29996109 | 4896 | 2018-07-10 | S6  | ? | old_coords_fix, revision 1381: complement(2609038..2610591)                        |
| SPBC2F12.10  | mrpl35 | MOD:00047 | tryptic phosphopeptide mapping assay evidence used in automatic assertion | T13 |                            | PMID:33823663 | 4896 | 2022-03-08 | T13 | ? | old_coords_fix, revision 20110324: complement(1719551..1720663)                    |
| SPBC582.07c  | rpn7   | MOD:00046 | tryptic phosphopeptide mapping assay evidence used in automatic assertion | S3  |                            | PMID:30726745 | 4896 | 2019-02-05 | S3  | ? | old_coords_fix, revision 8404: complement(430551..431780)                          |
| SPBC582.07c  | rpn7   | MOD:00046 | tryptic phosphopeptide mapping assay evidence used in automatic assertion | S5  |                            | PMID:30726745 | 4896 | 2019-02-05 | S5  | ? | old_coords_fix, revision 8404: complement(430551..431780)                          |
| SPCC825.04c  | naa40  | MOD:00046 | tryptic phosphopeptide mapping assay evidence used in automatic assertion | S11 |                            | PMID:30726745 | 4896 | 2019-02-05 | S11 | ? | old_coords_fix, revision 8405: complement(1030256..1030870)                        |
| SPCC825.04c  | naa40  | MOD:00048 | tryptic phosphopeptide mapping assay evidence used in automatic assertion | Y7  |                            | PMID:30726745 | 4896 | 2019-02-05 | Y7  | ? | old_coords_fix, revision 8405: complement(1030256..1030870)                        |
| SPCP1E11.06  | apl4   | MOD:00047 | mass spectrometry evidence                                                | T3  |                            | PMID:23297348 | 4896 | 2013-01-07 | T3  | ? | old_coords_fix, revision 8405: 2401980..2404577                                    |
| SPCP1E11.06  | apl4   | MOD:00047 | mass spectrometry evidence                                                | T4  |                            | PMID:23297348 | 4896 | 2013-01-07 | T4  | ? | old_coords_fix, revision 8405: 2401980..2404577                                    |
|              |        |           |                                                                           |     |                            |               |      |            |     |   |                                                                                    |

**Comment by ValWood** [comment]
I think this is a good plan. However, I wonder if the change to mmb1 is correct? The papers cited are PHong Tran and Nick Rhinds. I had a scan of Phong's paper (main and supp) and I could not find any report of a gene prediction error. Could you ask him?

If the N-term change came from Nick's data, I think this could only be because the mapped TSS was inside the old  gene prediction. However, the current TSS  would clearly allow for the original translation.
I tried to FASTA but there is no conservation in this region as far as I can see.

@juanmatacambridge  do you have translation start sites mapped for mmb1?
Thanks
val

**Comment by ValWood** [comment]
Yep the gene structure alteration. The warning on the gene page has these 2 references.

I checked all the others and they were part of this work
https://github.com/pombase/curation/issues/3024
the alterations were made to bring the translation inside the major TSS  (and sometimes also improve the homology)

**Comment by manulera** [comment]
Ok, I have written to Phong about mmb1, the others you think we can safely delete the annotations?

**Comment by ValWood** [comment]
I think so. We do not lose much if they are correct, but I think the current translations are right. If they turn out to have alternative translation starts ewe can deal with that later.

**Comment by manulera** [comment]
I added all changes except the mmb1 ones in svn revision 9038, see the diff below.

```diff
Index: trunk/external_data/modification_files/PMID_23297348_modifications.tsv
===================================================================
--- trunk/external_data/modification_files/PMID_23297348_modifications.tsv	(revision 9037)
+++ trunk/external_data/modification_files/PMID_23297348_modifications.tsv	(working copy)
@@ -484,8 +484,6 @@
 SPCC962.02c	bir1	MOD:00046	ECO:0001096	S878		PMID:23297348	4896	2013-01-07
 SPCC962.02c	bir1	MOD:00047	ECO:0001096	T831		PMID:23297348	4896	2013-01-07
 SPCP1E11.04c	pal1	MOD:00046	ECO:0001096	S370		PMID:23297348	4896	2013-01-07
-SPCP1E11.06	apl4	MOD:00047	ECO:0001096	T3		PMID:23297348	4896	2013-01-07
-SPCP1E11.06	apl4	MOD:00047	ECO:0001096	T4		PMID:23297348	4896	2013-01-07
 SPCP1E11.11	puf6	MOD:00046	ECO:0001096	S100		PMID:23297348	4896	2013-01-07
 SPCP1E11.11	puf6	MOD:00046	ECO:0001096	S101		PMID:23297348	4896	2013-01-07
 SPCP1E11.11	puf6	MOD:00046	ECO:0001096	S36		PMID:23297348	4896	2013-01-07
Index: trunk/external_data/modification_files/PMID_30726745_modifications.tsv
===================================================================
--- trunk/external_data/modification_files/PMID_30726745_modifications.tsv	(revision 9037)
+++ trunk/external_data/modification_files/PMID_30726745_modifications.tsv	(working copy)
@@ -9074,7 +9074,6 @@
 SPAC4F10.20	grx1	MOD:00046	ECO:0007464	S96		PMID:30726745	4896	2019-02-05
 SPBC365.07c		MOD:00046	ECO:0007464	S420		PMID:30726745	4896	2019-02-05
 SPBC1A4.08c	cct3	MOD:00046	ECO:0007464	S521		PMID:30726745	4896	2019-02-05
-SPAC3H1.05		MOD:00046	ECO:0007464	S12		PMID:30726745	4896	2019-02-05
 SPCC16C4.03	pin1	MOD:00046	ECO:0007464	S64		PMID:30726745	4896	2019-02-05
 SPACUNK4.07c	cta4	MOD:00046	ECO:0007464	S845		PMID:30726745	4896	2019-02-05
 SPCC645.12c		MOD:00046	ECO:0007464	S39		PMID:30726745	4896	2019-02-05
@@ -10060,8 +10059,6 @@
 SPAC23A1.17	bbc1	MOD:00046	ECO:0007464	S916		PMID:30726745	4896	2019-02-05
 SPAC24B11.06c	sty1	MOD:00048	ECO:0007464	Y173		PMID:30726745	4896	2019-02-05
 SPAC8C9.15c	tif225	MOD:00046	ECO:0007464	S500		PMID:30726745	4896	2019-02-05
-SPCC825.04c	naa40	MOD:00046	ECO:0007464	S11		PMID:30726745	4896	2019-02-05
-SPCC825.04c	naa40	MOD:00048	ECO:0007464	Y7		PMID:30726745	4896	2019-02-05
 SPAC26F1.03	pda1	MOD:00046	ECO:0007464	S310		PMID:30726745	4896	2019-02-05
 SPAC56F8.05c	mug64	MOD:00047	ECO:0007464	T109		PMID:30726745	4896	2019-02-05
 SPCC737.07c		MOD:00046	ECO:0007464	S133		PMID:30726745	4896	2019-02-05
@@ -10309,8 +10306,6 @@
 SPAC13G6.02c	rps101	MOD:00046	ECO:0007464	S251		PMID:30726745	4896	2019-02-05
 SPAC26H5.12	rpo41	MOD:00047	ECO:0007464	T892		PMID:30726745	4896	2019-02-05
 SPAC26H5.12	rpo41	MOD:00048	ECO:0007464	Y898		PMID:30726745	4896	2019-02-05
-SPBC582.07c	rpn7	MOD:00046	ECO:0007464	S3		PMID:30726745	4896	2019-02-05
-SPBC582.07c	rpn7	MOD:00046	ECO:0007464	S5		PMID:30726745	4896	2019-02-05
 SPCC16A11.16c	rpn1302	MOD:00047	ECO:0007464	T135		PMID:30726745	4896	2019-02-05
 SPCC16A11.16c	rpn1302	MOD:00047	ECO:0007464	T136		PMID:30726745	4896	2019-02-05
 SPAC1250.05	rpl3002	MOD:00046	ECO:0007464	S20		PMID:30726745	4896	2019-02-05
Index: trunk/external_data/modification_files/PMID_33823663_modifications.tsv
===================================================================
--- trunk/external_data/modification_files/PMID_33823663_modifications.tsv	(revision 9037)
+++ trunk/external_data/modification_files/PMID_33823663_modifications.tsv	(working copy)
@@ -4054,7 +4054,6 @@
 SPBC2F12.13		MOD:00046	ECO:0007464	S829		PMID:33823663	4896	2022-03-08
 SPBC2F12.10		MOD:00046	ECO:0007464	S12		PMID:33823663	4896	2022-03-08
 SPBC2F12.10		MOD:00046	ECO:0007464	S245		PMID:33823663	4896	2022-03-08
-SPBC2F12.10		MOD:00047	ECO:0007464	T13		PMID:33823663	4896	2022-03-08
 SPBC2F12.08c		MOD:00046	ECO:0007464	S384		PMID:33823663	4896	2022-03-08
 SPBC2F12.07c		MOD:00046	ECO:0007464	S11		PMID:33823663	4896	2022-03-08
 SPBC2F12.05c		MOD:00046	ECO:0007464	S384		PMID:33823663	4896	2022-03-08

```

**Comment by manulera** [comment]
This ticket is waiting on an answer for the mmb1 gene structure by Phong

**Comment by manulera** [comment]
We could not get an answer regarding the starting ATG of mmb1, so we removed the modification residues in revision 9042.

```diff
Index: trunk/external_data/modification_files/PMID_29996109_modifications.tsv
===================================================================
--- trunk/external_data/modification_files/PMID_29996109_modifications.tsv      (revision 9041)
+++ trunk/external_data/modification_files/PMID_29996109_modifications.tsv      (working copy)
@@ -3500,7 +3500,6 @@
 SPBC25B2.07c           MOD:00046       ECO:0007464     S376            PMID:29996109   4896    2018-07-10
 SPBC25B2.07c           MOD:00046       ECO:0007464     S381    present_during(GO:0000087)      PMID:29996109   4896    2018-07-10
 SPBC25B2.07c           MOD:00046       ECO:0007464     S383            PMID:29996109   4896    2018-07-10
-SPBC25B2.07c           MOD:00046       ECO:0007464     S4              PMID:29996109   4896    2018-07-10
 SPBC25B2.07c           MOD:00046       ECO:0007464     S409            PMID:29996109   4896    2018-07-10
 SPBC25B2.07c           MOD:00046       ECO:0007464     S410            PMID:29996109   4896    2018-07-10
 SPBC25B2.07c           MOD:00046       ECO:0007464     S411            PMID:29996109   4896    2018-07-10
@@ -3511,7 +3510,6 @@
 SPBC25B2.07c           MOD:00046       ECO:0007464     S446            PMID:29996109   4896    2018-07-10
 SPBC25B2.07c           MOD:00046       ECO:0007464     S447            PMID:29996109   4896    2018-07-10
 SPBC25B2.07c           MOD:00046       ECO:0007464     S455    present_during(GO:0000085)      PMID:29996109   4896    2018-07-10
-SPBC25B2.07c           MOD:00046       ECO:0007464     S6              PMID:29996109   4896    2018-07-10
 SPBC25B2.07c           MOD:00047       ECO:0007464     T129            PMID:29996109   4896    2018-07-10
 SPBC25B2.07c           MOD:00047       ECO:0007464     T257            PMID:29996109   4896    2018-07-10
 SPBC25B2.07c           MOD:00047       ECO:0007464     T304            PMID:29996109   4896    2018-07-10
Index: trunk/external_data/modification_files/PMID_33823663_modifications.tsv
===================================================================
--- trunk/external_data/modification_files/PMID_33823663_modifications.tsv      (revision 9041)
+++ trunk/external_data/modification_files/PMID_33823663_modifications.tsv      (working copy)
@@ -4356,7 +4356,6 @@
 SPBC25B2.10            MOD:00046       ECO:0007464     S297            PMID:33823663   4896    2022-03-08
 SPBC25B2.10            MOD:00047       ECO:0007464     T48             PMID:33823663   4896    2022-03-08
 SPBC25B2.09c           MOD:00046       ECO:0007464     S13             PMID:33823663   4896    2022-03-08
-SPBC25B2.07c           MOD:00046       ECO:0007464     S4              PMID:33823663   4896    2022-03-08
 SPBC25B2.07c           MOD:00046       ECO:0007464     S114            PMID:33823663   4896    2022-03-08
 SPBC25B2.07c           MOD:00046       ECO:0007464     S130            PMID:33823663   4896    2022-03-08
 SPBC25B2.07c           MOD:00046       ECO:0007464     S186            PMID:33823663   4896    2022-03-08
```
