### ISSUE TITLE
Wrongly labelled gene?

### ISSUE THREAD

**Issue by manulera** [pombase/allele_qc#64]
Hi @ValWood,

In this paper: https://www.pombase.org/reference/PMID:25720772

The modifications from `mug143` do not match the protein sequence. They are likely misanotated because `mug143` has never changed gene structure, and it has 121 aminoacids, while in our annotations residue `Y343` is mentioned.

I checked if there is a protein that would match all the residues annotated to `mug143` that do not match, and I find that `dbs2` matches all residues, so likely these protein modification annotations belong to `dbs2`. Actually, their systematic ids are consecutive: `SPAC167.05` for `dbs2` and `SPAC167.06c` for `mug143`, so I suspect that this was indeed a mistake. If you give me the green light, I will fix those.

| systematic_id | primary_name | modification | evidence                                                                  | sequence_position | annotation_extension | reference     | taxon | date       | sequence_error |
| ------------- | ------------ | ------------ | ------------------------------------------------------------------------- | ----------------- | -------------------- | ------------- | ----- | ---------- | -------------- |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S107              |                      | PMID:25720772 | 4896  | 2016-06-27 | S107           |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S103              |                      | PMID:25720772 | 4896  |  | S103           |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S110              |                      | PMID:25720772 | 4896  |  | S110           |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S12               |                      | PMID:25720772 | 4896  |  | S12            |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S132              |                      | PMID:25720772 | 4896  |  | S132           |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S134              |                      | PMID:25720772 | 4896  |  | S134           |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S143              |                      | PMID:25720772 | 4896  |  | S143           |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S145              |                      | PMID:25720772 | 4896  |  | S145           |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S148              |                      | PMID:25720772 | 4896  |  | S148           |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S149              |                      | PMID:25720772 | 4896  |  | S149           |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S15               |                      | PMID:25720772 | 4896  |  | S15            |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S151              |                      | PMID:25720772 | 4896  |  | S151           |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S154              |                      | PMID:25720772 | 4896  |  | S154           |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S157              |                      | PMID:25720772 | 4896  |  | S157           |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S18               |                      | PMID:25720772 | 4896  |  | S18            |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S333              |                      | PMID:25720772 | 4896  |  | S333           |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S335              |                      | PMID:25720772 | 4896  |  | S335           |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S345              |                      | PMID:25720772 | 4896  |  | S345           |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S347              |                      | PMID:25720772 | 4896  |  | S347           |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S552              |                      | PMID:25720772 | 4896  |  | S552           |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S554              |                      | PMID:25720772 | 4896  |  | S554           |
| SPAC167.06c   | mug143       | MOD:00046    | tryptic phosphop... | S590              |                      | PMID:25720772 | 4896  |  | S590           |
| SPAC167.06c   | mug143       | MOD:00047    | tryptic phosphop... | T106              |                      | PMID:25720772 | 4896  |  | T106           |
| SPAC167.06c   | mug143       | MOD:00047    | tryptic phosphop... | T144              |                      | PMID:25720772 | 4896  |  | T144           |
| SPAC167.06c   | mug143       | MOD:00047    | tryptic phosphop... | T152              |                      | PMID:25720772 | 4896  |  | T152           |
| SPAC167.06c   | mug143       | MOD:00047    | tryptic phosphop... | T339              |                      | PMID:25720772 | 4896  |  | T339           |
| SPAC167.06c   | mug143       | MOD:00048    | tryptic phosphop... | Y343              |                      | PMID:25720772 | 4896  |  | Y343           |

**Comment by ValWood** [comment]
Yes good catch!

**Comment by manulera** [comment]
This is now fixed in the svn repository (revision 9037)
