### ISSUE TITLE
PMID:1 allele in canto allele dump

### ISSUE THREAD

**Issue by manulera** [pombase/allele_qc#67]
Hi @kimrutherford, I find this allele in the file https://curation.pombase.org/data/pombe-allele-table.tsv from the canto allele dumps. It is not in PomBase, though. Is this from the canto test?

```
SPCC16C4.22	F124D	dpb3	dpb3-a		partial deletion and amino acid change	PMID:1	1	4666975359de04dd
```

**Comment by manulera** [comment]
I see that the section exists in the "normal canto" https://curation.pombase.org/pombe/curs/4666975359de04dd

**Comment by kimrutherford** [comment]
Hi Manu.  We have the PMID:1 session for testing in the main Canto.  We make sure it's never approved to prevent the session content ending up in Chado.

The script that generates `pombe-allele-table.tsv` currently exports all alleles from all session, even the non-approved ones.  Do you think I should change the script to only export approved sessions?  Or maybe approved sessions and submitted/in-approval sessions?

**Comment by manulera** [comment]
It's ok. It was just to double check with you. I will just close the issue.
