### ISSUE TITLE
How it looks right now

### ISSUE THREAD

**Issue by manulera** [pombase/allele_qc#7]
Hello @kimrutherford and @ValWood.

I finished, took quite a bit more than I anticipated. How it's looking now:

```
> auto-fix alleles: 1117
   syntax_error 311
   type_error 58
   type_error_and_syntax_error 20
   unknown_in_description 682
   update_coordinates 46

> need_supervision: 150
   coordinate_change_no_mutation 12
   coordinate_change_creates_error 10
   shift_coordinates 124
   update_and_shift_coordinates 4

> cannot fix alleles: 455
   nucleotide alleles: 183
   aminoacid alleles: 258
   disruption alleles: 14

   sequence_error: 334 of which 134 nucleotide
   pattern_error: 96
   invalid_error: 25
```

For the non self-evident:

- `type_error`: the allele_type has to be changed
- `unknown_in_description`: The description is `unknown`. I think it should be left empty instead (we have both instances in the database). `unknown` is also already in the allele_type
- `need_supervision`: alleles that would need a quick check to decide whether to accept the proposed auto-fix:
   - `coordinate_change_no_mutation`: for alleles in which the coordinate of the genes changed, but since they were partial deletion, the original coordinates referred to no aminoacid E.g. before change: deletion of 120-150, after change deletion of 130-160. A decission based on the other alleles in the session has to be made.
   - `coordinate_change_creates_error`: for alleles in which the coordinate of the genes changes, and there was no error in the sequence before, and introducing the changes has created an error (very likely they already used the right coordinates).
   - `shift_coordinates`: for alleles with sequence errors, in which shifting the coordinate by 1 fixes the error. E.g. there is no V123, but there is V122. Some alleles have all aminoacid shifted by one, clearly indicating that at least for those the fix makes sense.
   - `update_and_shift_coordinates`: for alleles in which the coordinate of the genes changes. Updating the gene coordinates + a shift by one as in `shift_coordinates` would fix the sequence error.
- `pattern_error`: The allele description is not captured by any of the regular expressions in the grammar.
- `invalid_error`: There is some inconsistency in the description. E.g. VAC-123-PP. There should be as many aminoacids in one side and the other if it is a substitution.

**Comment by manulera** [comment]
We can discuss the implementation and how to go aobut it in one of the next calls.

**Comment by kimrutherford** [comment]
> auto-fix alleles: 1117

Thanks Manu.  This is going be very helpful.
