### ISSUE TITLE
CTD support

### ISSUE THREAD

**Issue by manulera** [pombase/allele_qc#96]

**Comment by manulera** [comment]
Hi @kimrutherford and @ValWood, I am already regretting doing this given the shortage of time, but I have added support for the CTD in the allele_qc in #98. Some notes in case you have to work something out for the future:

* In pombe there are two genes with CTD (c-terminal domain) repeats: rpb1 and spt5 (see https://github.com/pombase/curation/issues/3312)
* rpb1 repeats are more consistent (all except one have the same length), and the sequence variation is little. We have 27 CTD alleles of rpb1.
* spt5 repeats are more different from each other in length and sequence, and we have few alleles.

Because of this, I have decided to make the CTD syntax pass the QC only for rpb1, and manually switched the spt5 alleles. Also, because several of spt5 alleles are not really spt5 variants, but a special construct where they introduce 7 consensus repeats after aminoacid 800.

For the rpb1 alleles, the QC passes, and they are translated into 😮very long😮 transvar variants.

For @kimrutherford, now there are two extra endpoints in the API, that you can use for the variant viewer, they transform an allele description `CTD-S2A`, or a protein modification sequence position `CTD-S2` into the "normal" syntax of variables and protein modifications.

<img width="700" alt="Screenshot 2023-08-16 at 17 32 04" src="https://github.com/pombase/allele_qc/assets/22526102/4cb80344-748e-488c-880e-6ab598b0a05b">

**Comment by ValWood** [comment]
Oh thank you, you should have left it but thank you!
